<?php
//数据库名
$DB_HOST=getenv("POSTGRES_HOST");
//数据库名
$DB_NAME=getenv("POSTGRES_DATABASE");
//数据库登录用户名
$DB_USER=getenv("POSTGRES_USER");
//数据库登录密码
$DB_PASS=getenv("POSTGRES_PASSWORD");
//几秒后跳转（等于0为关闭跳转页面）
$JUMP_TIME=1;
//站点名称
$TITLE="云电短链";
//生成短链的长度
$URL_SHORTENER_LENGHT=6;
//是否开启人机验证（注意，使用本功能，请务必开启php的GD库，当然一般默认是开启的）
$IMAGE_VERIFICATION=true;